### ISSUE TITLE
systemd support

### ISSUE THREAD

**Issue by dibalavs** [steps39/dtgbot#11]
Hi,
The most of modern distro (ubuntu, arch, ...) are using systemd initialization.
I think it is good idea to write systemd unit file.
Also As I understand profile initialization should be converted to EnvironmentFile compatible way.
and pid file should be eliminated.

**Comment by steps39** [comment]
Hi,
It is in the long term plan to make dtgbot easier to install and more robust, I need to understand systemd before doing this.

**Comment by jvanderzande** [comment]
The Stability-and-new-install branch has systemd support.

**Comment by steps39** [comment]
Hi Jos,

Thanks very much for responding to the 2 issues, great to see people are
using it.

I still plan to update my system sometime, but no idea when I will get
around to it.

Best wishes, Simon

Waste Group Leader - Climate Action Stokesley and Villages
https://climateactionstokesleyandvillages.org
Co-ordinator - Stokesley and Villages Repair Cafe
https://climateactionstokesleyandvillages.org/waste/stokesley-and-villages-repair-cafe/
Reclaim Our Sea - North East Coast
https://northeastfc.uk
07711 771291
