### ISSUE TITLE
Error in LUA

### ISSUE THREAD

**Issue by EvelRus** [steps39/dtgbot#16]
`sudo service dtgbot restart` and...
```
/usr/bin/lua5.2: error loading module 'socket.core' from file '/usr/local/lib/lua/5.2/socket/core.so':
        /usr/local/lib/lua/5.2/socket/core.so: wrong ELF class: ELFCLASS32
stack traceback:
        [C]: in ?
        [C]: in function 'require'
        /usr/local/share/lua/5.2/socket.lua:12: in main chunk
        [C]: in function 'require'
        /usr/local/share/lua/5.2/socket/http.lua:10: in main chunk
        [C]: in function 'require'
        /home/pi/dtgbot/dtgbot.lua:114: in main chunk
        [C]: in ?
```

**Comment by bjbaerken** [comment]
I have got the same error.

**Comment by jvanderzande** [comment]
Did you follow the install process steps and install the extra user libraries?

**Comment by bjbaerken** [comment]
Yes. I followed 
https://www.domoticz.com/wiki/Remote_Control_of_Domoticz_by_Telegram_Bot
Installed the files from: https://www.domoticz.com/forum/viewtopic.php?f=21&t=7279 
I still have this error:
/usr/bin/lua5.2: error loading module 'ssl.core' from file '/usr/local/lib/lua/5.2/ssl.so':
        libssl.so.1.0.0: cannot open shared object file: No such file or directory
stack traceback:
        [C]: in ?
        [C]: in function 'require'
        /usr/local/share/lua/5.2/ssl.lua:7: in main chunk
        [C]: in function 'require'
        /usr/local/share/lua/5.2/ssl/https.lua:10: in main chunk
        [C]: in function 'require'
        /home/pi/dtgbot/dtgbot.lua:116: in main chunk
        [C]: in ?

**Comment by jvanderzande** [comment]
Have a look here which seem to describe your issue and how it was solved https://www.domoticz.com/forum/viewtopic.php?f=21&t=7279&p=203049&hilit=Core#p208229

Jos

**Comment by EvelRus** [comment]
Yes, I forgot about those two files from the topic, I'm sorry. thanks

**Comment by EvelRus** [comment]
> Yes. I followed
> https://www.domoticz.com/wiki/Remote_Control_of_Domoticz_by_Telegram_Bot
> Installed the files from: https://www.domoticz.com/forum/viewtopic.php?f=21&t=7279
> I still have this error:
> /usr/bin/lua5.2: error loading module 'ssl.core' from file '/usr/local/lib/lua/5.2/ssl.so':
> libssl.so.1.0.0: cannot open shared object file: No such file or directory
> stack traceback:
> [C]: in ?
> [C]: in function 'require'
> /usr/local/share/lua/5.2/ssl.lua:7: in main chunk
> [C]: in function 'require'
> /usr/local/share/lua/5.2/ssl/https.lua:10: in main chunk
> [C]: in function 'require'
> /home/pi/dtgbot/dtgbot.lua:116: in main chunk
> [C]: in ?

libssl 1.0.0 has been updated to version 1.0.2 and back to none. So look where that version lies
