### ISSUE TITLE
dtgbot not working

### ISSUE THREAD

**Issue by XSlaY** [steps39/dtgbot#17]
Hello,
My dgtbot is not working. 
I created a telegram bot few days ago and it's working well (domoticz notifications works perfectly)
I followed the wiki (Remote Control of Domoticz by Telegram Bot) step by step but didn't succeed to make it work. 

Monit says for dtgbot "**Execution failed / dpesan't exist**"
and for dtgloop "**OK**"

With **sudo service dtgbot status** I get

_dtgbot.service - LSB: A Telegram bot designed to control Domoticz
   Loaded: loaded (/etc/init.d/dtgbot; generated)
   Active: active (exited) since Sat 2020-01-25 20:57:12 CET; 3min 30s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 3241 ExecStart=/etc/init.d/dtgbot start (code=exited, status=0/SUCCESS)

janv. 25 20:57:12 raspberrypi systemd[1]: Starting LSB: A Telegram bot designed to control Domoticz...
janv. 25 20:57:12 raspberrypi dtgbot[3241]: Starting Telegram Bot for Domoticz ... Done.
janv. 25 20:57:12 raspberrypi systemd[1]: Started LSB: A Telegram bot designed to control Domoticz._

Any clue what could my mistake?

Thanks

**Comment by jvanderzande** [comment]
For starters I would need yo see your dtg.log to see what happens. Pls email that to me as attachment so I can have a look.
Jos

**Comment by XSlaY** [comment]
Hi,
Problem was due to missing lib.
Solution was

sudo apt-get update
sudo apt-get install libssl1.0.0

Math

**Comment by bjbaerken** [comment]
Yes that works. I did have a newer version of libssl but you need the 1.0.0
