### ISSUE TITLE
Raw CURL reply

### ISSUE THREAD

**Issue by Welsyntoffie** [steps39/dtgbot#18]
I think this a dtgbot problem.
When I send the command "systemstatus" I get the responses I im looking for, but then I get another reply that I do not want to see.
How do I stop Recieved Message 3...

Send Command...
Pieter, [27.07.21 15:49]
systemstatus

Recieved Message 1
Arduino_Home, [27.07.21 15:49]
Please wait, gathering data...

Recieved Message 2
Arduino_Home, [27.07.21 15:49]
-CPU temperature: 36.9°C
-CPU Usage: 9.09 %
-Memory Usage: 39.03 %
-UpTime: 15.24 h
-Domoticz update available! (version 13191)

(Don't want this)
Recieved Message 3 
Arduino_Home, [27.07.21 15:49]
[In reply to Pieter]
t_name":"Pieter","type":"private"},"date":1627393779,"text":"-CPU temperature: 36.9\u00b0C\n-CPU Usage: 9.09 %\n-Memory Usage: 39.03 %\n-UpTime: 15.24 h\n-Domoticz update available! (version 13191)"}}

**Comment by jvanderzande** [comment]
I have already provided an answer in the Domoticz thread we have going. :) 
https://www.domoticz.com/forum/viewtopic.php?p=277632#p277632

Lets finish this issue there and I will commit the proposed change after you tested it. 
It also means that all other provided bash script need to be reviewed and likely updated.
Pull requests are welcome. :)
