### ISSUE TITLE
Possible typo in dtg_main_functions.lua

### ISSUE THREAD

**Issue by anyremote** [steps39/dtgbot#22]
if **msg_type == "voice"** then
          Print_to_Log(0, "!! Voice file received but voice.sh or lua not found to process it. skipping the message.")
          Telegram_SendMessage(msg_from, "⚡️ voice.sh or lua missing?? ⚡️", msg_id)
        elseif **msg_type == "voice"** then
          Print_to_Log(0, "!! Video file received but video_note.sh or lua not found to process it. Skipping the message.")
          Telegram_SendMessage(msg_from, "⚡️ video_note.sh or lua missing?? ⚡️", msg_id)

seems second "voice" should be "video"

**Comment by jvanderzande** [comment]
Fixed...   thanks
