### ISSUE TITLE
new download function

### ISSUE THREAD

**Issue by pietrondo** [steps39/dtgbot#4]
Hi, I'm new on dtgbot.. I would add new function to the bot. 
I need to download "thing" (curl or wget) using the bot integrated with domoticz.
I think I need to add a new "module" in lua folder.
The problem now is to create a "new function" that tells:
download a link in a specific folder of raspberry (where domoticz is installed).
Someone could help me?

thx

**Comment by jvanderzande** [comment]
Should be just a matter of copying one of the existing scripts in the bash or lua subdirectories and adapting it to your needs.
I am closing this issue and come to the forum when you want to discuss this or have further questions.
